#!/bin/sh
#
# CONFIG
#

HOST=<your host adress>
LOGIN=<host login id for this host in OVH services>
PASSWORD=<password for this host login id in OVH services>
PATH_LOG=/home/pi/Desktop/log/dynhost
CURRENT_DATE=$(date)
echo "Raspberry dynhost version 1.0 - Date: $CURRENT_DATE"

#
# GET IPs
#

HOST_IP=$(dig +short $HOST)
CURRENT_IP=$(curl -4 ifconfig.co)

echo "HOST_IP: $HOST_IP"
echo "CURRENT_IP: $CURRENT_IP"

#
# DO THE WORK
#
if [ -z $CURRENT_IP ] || [ -z $HOST_IP ]
then
        echo "No IP retrieved" >> $PATH_LOG
else
        if [ "$HOST_IP" != "$CURRENT_IP" ]
        then
                echo "$CURRENT_DATE"": Current IP:" "$CURRENT_IP" "and" "host IP:" "$HOST_IP" "   IP has changed!" >> $PATH_LOG
                RES=$(curl --user "$LOGIN:$PASSWORD" "https://www.ovh.com/nic/update?system=dyndns&hostname=$HOST&myip=$CURRENT_IP")                
		echo "Result request dynHost:" >> $PATH_LOG
                echo "$RES" >> $PATH_LOG
        else
                echo "$CURRENT_DATE"": Current IP:" "$CURRENT_IP" "and" "Host IP:" "$HOST_IP" "   IP has not changed" >> $PATH_LOG
        fi
fi
